# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2


jobs:
  test35:
    docker:
      - image: python:3.5
    steps: &test_steps
      - checkout
      - run:
          name: install tox
          command: |
            pip install tox
      - run:
          name: tox -r to install and run tests and flake
          command: |
            tox -r --skip-missing-interpreters

  publish35:
    docker:
      - image: python:3.5
    steps: &publish_steps
      - checkout
      - run:
          name: set PyPI creds in .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = OsmoSystems" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: upgrade build tooling
          command: pip install --upgrade setuptools wheel twine
      - run:
          name: build package
          command: |
            export PATCH_VERSION=$CIRCLE_BUILD_NUM
            python setup.py bdist_wheel
      - run:
          name: publish
          command: twine upload dist/*

  test36:
    docker:
      - image: python:3.6
    steps: *test_steps

  publish36:
    docker:
      - image: python:3.6
    steps: *publish_steps

workflows:
  version: 2
  test_and_publish:
    jobs:
      - test35
      - test36
      - approve_publish:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: master
      - publish35:
          context: pypi
          requires:
            - approve_publish
      - publish36:
          context: pypi
          requires:
            - approve_publish
